// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health/getalllifestyledata/{limit}/{page}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Foydalanuvchilarning barcha lifestyle (turmush tarzi) ma'lumotlarini olish uchun ishlatiladi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LifestyleData"
                ],
                "summary": "Get All Lifestyle Data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Cheklov (sahifadagi yozuvlar soni)",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Sahifa (qaysi sahifadagi yozuvlar ko'rinadi)",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Ma'lumotlar muvaffaqiyatli qaytarildi",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.GetAllLifestyleDataResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid limit or page parameter\" \"Noto'g'ri limit yoki sahifa parametri",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error\" \"Serverda xatolik yuz berdi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/lifestyleAdd": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Yangi turmush tarzi ma'lumotlarini qo'shadi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LifestyleData"
                ],
                "summary": "Turmush tarzi ma'lumotlarini qo'shish",
                "parameters": [
                    {
                        "description": "Turmush tarzi ma'lumotlari",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/health_analytics.AddLifestyleDataRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.AddLifestyleDataResponse"
                        }
                    },
                    "400": {
                        "description": "Noto'g'ri so'rov",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ichki server xatoligi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/lifestyleDel/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Turmush tarzi ma'lumotlarini ID bo'yicha o'chirish",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LifestyleData"
                ],
                "summary": "Turmush tarzi ma'lumotlarini o'chirish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Turmush tarzi ma'lumotlari ID si",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.DeleteLifestyleDataResponse"
                        }
                    },
                    "500": {
                        "description": "Ichki server xatoligi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/lifestyleGet/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Turmush tarzi ma'lumotlarini ID bo'yicha olish",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LifestyleData"
                ],
                "summary": "Turmush tarzi ma'lumotlarini olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Turmush tarzi ma'lumotlari ID si",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.GetLifestyleDataResponse"
                        }
                    },
                    "500": {
                        "description": "Ichki server xatoligi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/lifestyleUp": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Mavjud turmush tarzi ma'lumotlarini yangilash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LifestyleData"
                ],
                "summary": "Turmush tarzi ma'lumotlarini yangilash",
                "parameters": [
                    {
                        "description": "Yangilanadigan turmush tarzi ma'lumotlari",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/health_analytics.UpdateLifestyleDataRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.UpdateLifestyleDataResponse"
                        }
                    },
                    "400": {
                        "description": "Noto'g'ri so'rov",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ichki server xatoligi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/medical_records/user/{userId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint allows you to list all medical records associated with a specific user ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MedicalRecords"
                ],
                "summary": "List all medical records for a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.ListMedicalRecordsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/medical_records/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint allows you to delete a medical record by its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MedicalRecords"
                ],
                "summary": "Delete a medical record by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Medical Record ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.DeleteMedicalRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/medical_recordsAdd": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint allows you to add a new medical record to the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MedicalRecords"
                ],
                "summary": "Add a new medical record",
                "parameters": [
                    {
                        "description": "Medical Record Data",
                        "name": "medicalRecord",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/health_analytics.AddMedicalRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.AddMedicalRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/medical_recordsGet/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint allows you to fetch a medical record by its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MedicalRecords"
                ],
                "summary": "Get a medical record by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Medical Record ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.GetMedicalRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/medical_recordsUp": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint allows you to update an existing medical record.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MedicalRecords"
                ],
                "summary": "Update a medical record",
                "parameters": [
                    {
                        "description": "Updated Medical Record Data",
                        "name": "medicalRecord",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/health_analytics.UpdateMedicalRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.UpdateMedicalRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/monitoring/{user_id}/realtime": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Foydalanuvchining real vaqt sog'liq monitoringini qaytaradi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Real vaqt sog'liq monitoringi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Foydalanuvchi ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.GetRealtimeHealthMonitoringResponse"
                        }
                    },
                    "500": {
                        "description": "Xatolik: Ichki server xatosi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/recommendationsAdd": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Foydalanuvchi uchun sog'liq bo'yicha tavsiyalarni yaratadi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Sog'liq bo'yicha tavsiyalar yaratish",
                "parameters": [
                    {
                        "description": "Tavsiyalar yaratish uchun ma'lumotlar",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/health_analytics.GenerateHealthRecommendationsRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.GenerateHealthRecommendationsResponse"
                        }
                    },
                    "400": {
                        "description": "Xatolik: Notog'ri so'rov",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Xatolik: Ichki server xatosi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/summary/{user_id}/daily": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Foydalanuvchining belgilangan kun uchun sog'liq hisobotini qaytaradi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Kunlik sog'liq hisobotini olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Foydalanuvchi ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kun (format: yyyy/mm/dd)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.GetDailyHealthSummaryResponse"
                        }
                    },
                    "500": {
                        "description": "Xatolik: Ichki server xatosi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/summary/{user_id}/weekly": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Foydalanuvchining belgilangan haftalik sog'liq hisobotini qaytaradi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Haftalik sog'liq hisobotini olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Foydalanuvchi ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Boshlang'ich sana (format: yyyy/mm/dd)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.GetWeeklyHealthSummaryResponse"
                        }
                    },
                    "500": {
                        "description": "Xatolik: Ichki server xatosi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/wearable-dataAdd": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint yangi kiyiladigan qurilma ma'lumotlarini qo'shadi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wearable-data"
                ],
                "summary": "Add Wearable Data",
                "parameters": [
                    {
                        "description": "Kiyiladigan qurilma ma'lumotlari",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/health_analytics.AddWearableDataRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.AddWearableDataResponse"
                        }
                    },
                    "400": {
                        "description": "bodydan malumotlarni olishda xatolik: \u003cerror_message\u003e",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "AddWearableData yuborishda xatolik: \u003cerror_message\u003e",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/wearable-dataDel/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint berilgan ID bo'yicha kiyiladigan qurilma ma'lumotlarini o'chiradi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wearable-data"
                ],
                "summary": "Delete Wearable Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kiyiladigan qurilma ma'lumotlari ID'si",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.DeleteWearableDataResponse"
                        }
                    },
                    "500": {
                        "description": "DeleteWearableData yuborishda xatolik: \u003cerror_message\u003e",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/wearable-dataGet/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint ID bo'yicha kiyiladigan qurilma ma'lumotlarini qaytaradi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wearable-data"
                ],
                "summary": "Get Wearable Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kiyiladigan qurilma ma'lumotlari ID'si",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.GetWearableDataResponse"
                        }
                    },
                    "500": {
                        "description": "GetWearableData yuborishda xatolik: \u003cerror_message\u003e",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/wearable-dataUp": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint mavjud kiyiladigan qurilma ma'lumotlarini yangilaydi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wearable-data"
                ],
                "summary": "Update Wearable Data",
                "parameters": [
                    {
                        "description": "Yangilangan kiyiladigan qurilma ma'lumotlari",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/health_analytics.UpdateWearableDataRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.UpdateWearableDataResponse"
                        }
                    },
                    "400": {
                        "description": "bodydan malumotlarni olishda xatolik: \u003cerror_message\u003e",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "UpdateWearableData yuborishda xatolik: \u003cerror_message\u003e",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/wearabledata/{limit}/{page}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint foydalanuvchilarning barcha wearable (kiyiladigan) ma'lumotlarini olish uchun ishlatiladi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wearable-data"
                ],
                "summary": "Get All Wearable Data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Cheklov (sahifadagi yozuvlar soni)",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Sahifa (qaysi sahifadagi yozuvlar ko'rinadi)",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Ma'lumotlar muvaffaqiyatli qaytarildi",
                        "schema": {
                            "$ref": "#/definitions/health_analytics.GetAllWearableDataResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid limit or page parameter\" \"Noto'g'ri limit yoki sahifa parametri",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error\" \"Serverda xatolik yuz berdi",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health_analytics.AddLifestyleDataRequest": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string"
                },
                "data_value": {
                    "type": "string"
                },
                "recorded_date": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "health_analytics.AddLifestyleDataResponse": {
            "type": "object",
            "properties": {
                "lifestyleData": {
                    "$ref": "#/definitions/health_analytics.LifestyleData"
                }
            }
        },
        "health_analytics.AddMedicalRecordRequest": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "string"
                },
                "record_date": {
                    "type": "string"
                },
                "record_type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "health_analytics.AddMedicalRecordResponse": {
            "type": "object",
            "properties": {
                "medical_record": {
                    "$ref": "#/definitions/health_analytics.MedicalRecord"
                }
            }
        },
        "health_analytics.AddWearableDataRequest": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string"
                },
                "data_value": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "recorded_timestamp": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "health_analytics.AddWearableDataResponse": {
            "type": "object",
            "properties": {
                "wearableData": {
                    "$ref": "#/definitions/health_analytics.WearableData"
                }
            }
        },
        "health_analytics.DeleteLifestyleDataResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "health_analytics.DeleteMedicalRecordResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "health_analytics.DeleteWearableDataResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "health_analytics.GenerateHealthRecommendationsRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "recommendation_type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "health_analytics.GenerateHealthRecommendationsResponse": {
            "type": "object",
            "properties": {
                "recommendations": {
                    "$ref": "#/definitions/health_analytics.HealthRecommendation"
                }
            }
        },
        "health_analytics.GetAllLifestyleDataResponse": {
            "type": "object",
            "properties": {
                "lifestyledata": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/health_analytics.LifestyleData"
                    }
                }
            }
        },
        "health_analytics.GetAllWearableDataResponse": {
            "type": "object",
            "properties": {
                "wearabledata": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/health_analytics.WearableData"
                    }
                }
            }
        },
        "health_analytics.GetDailyHealthSummaryResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "recommendation_type": {
                    "type": "string"
                }
            }
        },
        "health_analytics.GetLifestyleDataResponse": {
            "type": "object",
            "properties": {
                "lifestyle_data": {
                    "$ref": "#/definitions/health_analytics.LifestyleData"
                }
            }
        },
        "health_analytics.GetMedicalRecordResponse": {
            "type": "object",
            "properties": {
                "medical_record": {
                    "$ref": "#/definitions/health_analytics.MedicalRecord"
                }
            }
        },
        "health_analytics.GetRealtimeHealthMonitoringResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "recommendation_type": {
                    "type": "string"
                }
            }
        },
        "health_analytics.GetWearableDataResponse": {
            "type": "object",
            "properties": {
                "wearable_data": {
                    "$ref": "#/definitions/health_analytics.WearableData"
                }
            }
        },
        "health_analytics.GetWeeklyHealthSummaryResponse": {
            "type": "object",
            "properties": {
                "health": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/health_analytics.HealthRecommendation"
                    }
                }
            }
        },
        "health_analytics.HealthRecommendation": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "recommendation_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "health_analytics.LifestyleData": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "data_type": {
                    "type": "string"
                },
                "data_value": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "recorded_date": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "health_analytics.ListMedicalRecordsResponse": {
            "type": "object",
            "properties": {
                "medical_records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/health_analytics.MedicalRecord"
                    }
                }
            }
        },
        "health_analytics.MedicalRecord": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "record_date": {
                    "type": "string"
                },
                "record_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "health_analytics.UpdateLifestyleDataRequest": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string"
                },
                "data_value": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "recorded_date": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "health_analytics.UpdateLifestyleDataResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "health_analytics.UpdateMedicalRecordRequest": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "record_date": {
                    "type": "string"
                },
                "record_type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "health_analytics.UpdateMedicalRecordResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "health_analytics.UpdateWearableDataRequest": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string"
                },
                "data_value": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "recorded_timestamp": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "health_analytics.UpdateWearableDataResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "health_analytics.WearableData": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "data_type": {
                    "type": "string"
                },
                "data_value": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "recorded_timestamp": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:50053",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "User Service API",
	Description:      "This is a sample server for a user service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
